gcc-crosssdk-initial_%.bbappend:Do not configure with initfini-array enabled
Default configuration for gcc-crosssddk-initial is now to enable initfini-array.
However, this works only for Linux so we disable it for mingw32.
Otherwise, (with SDKMACHINE=x86_64-mingw32) we will eventually encounter errors such as:

 Assembler messages:
 Error: invalid instruction suffix for `push'
 Error: invalid instruction suffix for `pop'

(LOCAL REV: NOT UPSTREAM) -- From yocto mailing list

Signed-off-by: Juro Bystricky <juro.bystricky@intel.com>
Signed-off-by: Mark Hatle <mark.hatle@windriver.com>